### ISSUE TITLE
[BE] 설계

### ISSUE THREAD

**Issue by jeremy0405** [jeremy0405/issue-tracker#3]
## 기능 요청사항

기능 구현을 위한 설계

## 요청 세부사항

- 도메인 설계
- 테이블 설계
- API 설계

**Comment by jeremy0405** [comment]
- 테이블 설계
- API 설계

[Google Sheet](https://docs.google.com/spreadsheets/d/1SGX8jnKHl9L7iTrNTYVyl9NaGwebUOWzfA9qoHxfKoI/edit?usp=sharing)

**Comment by who-hoo** [comment]
### ERD
URL : https://aquerytool.com/aquerymain/index/?rurl=9fb1fcf4-53d0-4fa9-8046-ae655f62ebb4&
Password : pu73d3
